ARG JAR_FILE=target/doolittle-contentlist-service.jar
FROM 965331111166.dkr.ecr.us-west-2.amazonaws.com/deployable/springboot:jdk-17

ENV NEW_RELIC_APP_NAME="doolittle-local-doolittle-contentlist;CTK-local"

